### ISSUE TITLE
Setup DCE and allow running either to compare without

### ISSUE THREAD

**Issue by LouisCAD** [gzoritchak/todokotlin#2]
Right now, Chrome Dev tools the app weighs 5.4MB in debug mode, which is quite heavy, making it impractical beyond of a local network.
It'd be nice to have a gradle task to run it with [DCE](https://kotlinlang.org/docs/reference/javascript-dce.html) enabled, and also a mnifier like UglifyJS or Google Closure Compiler, to see how to set it up, and see how it compares, including as code is added.

**Comment by gzoritchak** [comment]
I've made some tests yesterday night. 
With DCE + Webpack + uglify, I end with a 1.1 MB single bundle file. When zipped, it takes 220 Ko, which is more acceptable.

I didn't push it yet because of some errors on Ktor-client dependencies.

**Comment by gzoritchak** [comment]
You can see DCE + Webpack + Uglify on the [axios branch](https://github.com/gzoritchak/todokotlin/tree/axios).
